# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'week6Assignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for week6Assignment
pod 'FittedSheets'
pod 'iOSDropDown'


end
